"""empty message

Revision ID: 5123538057c7
Revises: da670d885e2f
Create Date: 2021-01-17 16:21:57.259764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5123538057c7'
down_revision = 'da670d885e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('roles', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'roles')
    # ### end Alembic commands ###
