"""empty message

Revision ID: 90773bf4ce25
Revises: b77e54a73c3f
Create Date: 2021-04-04 01:17:15.055556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90773bf4ce25'
down_revision = 'b77e54a73c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classSessions', sa.Column('endTime', sa.DateTime(), nullable=True))
    op.add_column('classSessions', sa.Column('startTime', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('realName', sa.String(), nullable=True))
    op.drop_column('students', 'name')
    op.add_column('teachers', sa.Column('realName', sa.String(), nullable=True))
    op.drop_column('teachers', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('teachers', 'realName')
    op.add_column('students', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('students', 'realName')
    op.drop_column('students', 'gender')
    op.drop_column('students', 'dob')
    op.drop_column('classSessions', 'startTime')
    op.drop_column('classSessions', 'endTime')
    # ### end Alembic commands ###
