"""empty message

Revision ID: 95873a9662eb
Revises: 453a87947c42
Create Date: 2021-03-13 19:12:11.922230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95873a9662eb'
down_revision = '453a87947c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('openID', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sessionKey', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessionKey')
    op.drop_column('users', 'openID')
    op.drop_column('teachers', 'avatar')
    # ### end Alembic commands ###
