"""empty message

Revision ID: da670d885e2f
Revises: 
Create Date: 2021-01-17 15:36:38.538018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da670d885e2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('pwhash', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('validated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'validated')
    op.drop_column('teachers', 'pwhash')
    op.drop_column('teachers', 'phone')
    op.drop_column('teachers', 'email')
    # ### end Alembic commands ###
