"""empty message

Revision ID: dbc692269e28
Revises: 201fbe71ac53
Create Date: 2021-05-04 23:09:33.620188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc692269e28'
down_revision = '201fbe71ac53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classSessions', sa.Column('attendance_call', sa.BOOLEAN(), nullable=True))
    op.add_column('classSessions', sa.Column('attendance_teacher', sa.INTEGER(), nullable=True))
    op.add_column('classSessions', sa.Column('attendance_time', sa.DATETIME(), nullable=True))
    op.create_foreign_key(None, 'classSessions', 'users', ['attendance_teacher'], ['id'])
    op.add_column('students', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('students', sa.Column('qr_code', sa.BLOB(), nullable=True))
    op.add_column('takingClasses', sa.Column('attended', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('takingClasses', 'attended')
    op.drop_column('students', 'qr_code')
    op.drop_column('students', 'create_time')
    op.drop_constraint(None, 'classSessions', type_='foreignkey')
    op.drop_column('classSessions', 'attendance_time')
    op.drop_column('classSessions', 'attendance_teacher')
    op.drop_column('classSessions', 'attendance_call')
    # ### end Alembic commands ###
